# Generated by Django 4.1.3 on 2023-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidwinners",
            name="winner",
        ),
        migrations.AddField(
            model_name="bidwinners",
            name="prod",
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name="bidwinners",
            name="winnerid",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
