# Generated by Django 4.1.3 on 2023-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_bidwinners_winner_bidwinners_prod_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="recordwinners",
            fields=[
                (
                    "winnerid",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("prod", models.CharField(default=0, max_length=50)),
                ("productname", models.CharField(max_length=50)),
                ("owneremail", models.CharField(max_length=50)),
                ("winneremail", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("phonenumber", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="bidwinners",
        ),
    ]
