# Generated by Django 4.1.3 on 2023-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="usersinformations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userfname", models.CharField(default="", max_length=50)),
                ("userlname", models.CharField(default="", max_length=50)),
                ("useremail", models.CharField(default="", max_length=50)),
                ("phonenumber", models.IntegerField(default=0)),
                ("useraddress", models.CharField(default="", max_length=300)),
                ("usercity", models.CharField(default="", max_length=50)),
                ("userpassword", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
