# Generated by Django 4.1.3 on 2023-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_usersinformations"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="useremail",
            field=models.CharField(default="", max_length=50),
        ),
    ]
