# Generated by Django 4.1.3 on 2023-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useremail", models.CharField(default="", max_length=50)),
                ("subject", models.CharField(default="", max_length=50)),
                ("message", models.CharField(default="", max_length=300)),
            ],
        ),
    ]
