# Generated by Django 4.1.3 on 2023-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="date",
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.CharField(max_length=1000),
        ),
    ]
