# Generated by Django 4.1.3 on 2023-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(default="", upload_to="shop/images/%y"),
        ),
    ]
