# Generated by Django 4.1.3 on 2023-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_product_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="bidder",
            fields=[
                ("bid", models.AutoField(primary_key=True, serialize=False)),
                ("pid", models.CharField(max_length=50)),
                ("bemail", models.EmailField(max_length=254)),
                ("bprice", models.CharField(max_length=50)),
            ],
        ),
    ]
