# Generated by Django 4.1.3 on 2023-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_bidder"),
    ]

    operations = [
        migrations.CreateModel(
            name="winner",
            fields=[
                ("productid", models.AutoField(primary_key=True, serialize=False)),
                ("productname", models.CharField(max_length=50)),
                ("owneremail", models.CharField(max_length=50)),
                ("winneremail", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
            ],
        ),
    ]
