# Generated by Django 4.1.3 on 2023-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="phonenumber",
            field=models.IntegerField(default=0),
        ),
    ]
