# Generated by Django 4.1.3 on 2023-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_winner_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="winnerid",
            field=models.AutoField(default="", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="winner",
            name="productid",
            field=models.CharField(max_length=50),
        ),
    ]
