# Generated by Django 4.1.3 on 2023-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_winner_winnerid_alter_winner_productid"),
    ]

    operations = [
        migrations.CreateModel(
            name="bidwinners",
            fields=[
                ("winnerid", models.AutoField(primary_key=True, serialize=False)),
                ("productid", models.CharField(max_length=50)),
                ("productname", models.CharField(max_length=50)),
                ("owneremail", models.CharField(max_length=50)),
                ("winneremail", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("phonenumber", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="winner",
            name="winnerid",
        ),
        migrations.AlterField(
            model_name="winner",
            name="productid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
